export const USER_VALID = 'USER_VALID';
export const REQUEST_LISTINGS_PENDING = 'REQUEST_LISTINGS_PENDING';
export const REQUEST_LISTINGS_SUCCESS = 'REQUEST_LISTINGS_SUCCESS';
export const REQUEST_LISTINGS_FAILED = 'REQUEST_LISTINGS_FAILED';